// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table bikes (BikepointID:string, Street:string, Neighbourhood:string, Latitude:real, Longitude:real, No_Bikes:long, No_Empty_Docks:long) 
.create-merge table bikes_final (BikepointID:string, Street:string, Neighbourhood:string, Latitude:real, Longitude:real, No_Bikes:long, No_Empty_Docks:long, MyTimestamp:datetime) 
.create-or-alter function with (skipvalidation = "true") bikes_transform() {
    bikes
    | extend MyTimestamp = datetime_add('hour', 2, now())
}
.alter table bikes policy streamingingestion "{\"IsEnabled\":true,\"HintAllocatedRate\":null,\"NumberOfRowStores\":null,\"SealIntervalLimit\":null,\"SealThresholdBytes\":null,\"UsageTags\":[],\"IsMaintenanceActive\":false}"
.alter table bikes_final policy update "[{\"IsEnabled\":true,\"Source\":\"bikes\",\"Query\":\"bikes_transform()\",\"IsTransactional\":true,\"PropagateIngestionProperties\":false,\"ManagedIdentity\":null}]"
